### ISSUE TITLE
the evaluation dataset CSP-100

### ISSUE THREAD

**Issue by beibeirory** [cxh0519/Progressive3D#1]
Thanks for your great work. Could you release the CSP-100 dataset?

**Comment by cxh0519** [comment]
CSP-100 dataset is a prompt list and has been shown in the Appx. of our Arxiv paper.

**Comment by beibeirory** [comment]
Thanks very much. When will you release your code?

**Comment by cxh0519** [comment]
Our code will open after the paper has been reviewed.
