### ISSUE TITLE
A problem about Overlapped Semantic Component Suppression

### ISSUE THREAD

**Issue by XiaokunSun** [cxh0519/Progressive3D#4]
Thank you for your excellent work, I would like to ask if the Overlapped Semantic Component Suppression strategy must require that the two prompts have strictly overlapping parts, if there is a semantic overlap but the prompts don't strictly overlap, can the strategy still work? 
For example, standard prompt: "a medieval soldier with metal armor|a medieval soldier with metal armor riding a terracotta wolf", and I shuffled the order of words or changed the description so that the semantics of the text remained the same, but the text no longer overlapped. The changed text: "a medieval soldier with metal armor|a medieval soldier wearing metal armor and riding a terracotta wolf“ or "a medieval soldier with metal armor riding a terracotta wolf|a medieval soldier with metal armor holding a golden axe and riding a terracotta wolf".  Does the Overlapped Semantic Component Suppression strategy still work after using the changed text?

**Comment by cxh0519** [comment]
Thanks for your attention!
Our OSCS is designed for semantic overlap and our experiments show that OSCS can work when two prompts are not strictly overlapped. For instance, if the source prompt is (A and B), Progressive3D achieves correct edits whether the target prompt is (A and B and C) or (A and C and B) in our experiments.
