### ISSUE TITLE
Some questions on the box configs.

### ISSUE THREAD

**Issue by Colezwhy** [cxh0519/Progressive3D#5]
Hi, thank you for the great job and congratulations! Very inspiring and solid work!

But I am wondering that what indeed is the box config about? Since in the README said box center and scale, but why the scales could be 0? And isn't the coordinate value of box center too small? I am very curious about it, would you please give me a more detailed explanation? That will be super helpful for me.

Thank you for your precious time!

**Comment by cxh0519** [comment]
The editable region is defined as box_info=[box center; box size]

**Comment by cxh0519** [comment]
The editable region is defined as box_info=[box center; box size]
Noticing that the space range is [-1, 1] in all axises, which means [0, 0, 0] is the center of the space.
For instance, [2.0, 0.5, 1.0, 0.0, 0.0, -0.6] demonstrate that the box's length is 2.0 in X-axis, 0.5 in Y-axis and 1.0 in Z-axis. And the center of the box is [0, 0, -0.6]

**Comment by Colezwhy** [comment]
> The editable region is defined as box_info=[box center; box size] Noticing that the space range is [-1, 1] in all axises, which means [0, 0, 0] is the center of the space. For instance, [2.0, 0.5, 1.0, 0.0, 0.0, -0.6] demonstrate that the box's length is 2.0 in X-axis, 0.5 in Y-axis and 1.0 in Z-axis. And the center of the box is [0, 0, -0.6]

Thank you, but isn't it box_info=[box size, box center]？

**Comment by cxh0519** [comment]
Sorry for the typo. The box_info is [box size, box center]. Thanks for your remind and I'll revise the README.
